name: test
on:
  push:
    branches:
      - 'main'
jobs:
  test_flagsmith_ssm:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    container: node:lts-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-2'
          role-to-assume: ${{secrets.AWS_ROLE}}
      - uses: ./
        with:
          FLAG_NAME: "test"
          FLAGSMITH_ENV_KEY: ${{Secrets.FLAGSMITH_ENV_KEY}}